services:
  mariadb:
    container_name: mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure # "on-failure", container will be restarted 


  nginx:           # with TLSv.1.2
    container_name: nginx
    volumes:
      - wordpress:$WP_PATH
    networks:
      - inception
    depends_on:
      - wordpress
      - toukoum
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:$WP_PATH
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis 
    restart: on-failure


  #bonus
  redis:
    container_name: redis
    env_file:
      - .env
    networks:
      - inception
    build: ./requirements/bonus/redis
    restart: on-failure

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    env_file: .env
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/nekfeu/wordpress
    restart: on-failure


  toukoum:
    build: ./requirements/bonus/toukoum
    container_name: toukoum
    networks:
      - inception



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jul/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jul/data/mariadb'



#network part
networks:
    inception:
      driver: bridge