


services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure # "on-failure", container will be restarted 


  nginx:           # with TLSv.1.2
    image: nginx
    container_name: nginx # name of the container
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:    # wordpress will be started after mariadb
      - mariadb
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jul/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jul/data/mariadb'



#network part
networks:
    inception:
      driver: bridge