services:
  mariadb:
    container_name: mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure


  nginx:
    container_name: nginx
    volumes:
      - wordpress:$WP_PATH
    networks:
      - inception
    depends_on:
      - wordpress
      - toukoum
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    expose:
      - 80

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:$WP_PATH
    networks:
      - inception
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    expose:
    - 9000


  #bonus
  redis:
    container_name: redis
    env_file:
      - .env
    networks:
      - inception
    build: ./requirements/bonus/redis
    restart: on-failure
    expose:
      - 6379

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
    ports:
      - "21:21"
    env_file: .env
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/nekfeu/wordpress
    restart: on-failure


  toukoum:
    build: ./requirements/bonus/toukoum
    container_name: toukoum
    networks:
      - inception
    restart: on-failure
    expose:
      - 80


  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - "4321:4321"


  prometheus:
    container_name: prometheus
    build:
      context: ./requirements/bonus/prometheus
      args:
        PROMETHEUS_VERSION: ${PROMETHEUS_VERSION}
        CONFIG_DIR: ${CONFIG_DIR}
        DATA_DIR: ${DATA_DIR}
    ports:
      - "9090:9090"
    volumes:
      - /data/prometheus:/var/lib/prometheus
    networks:
      - inception
    restart: on-failure
    depends_on:
      - wordpress
  
  grafana:
    container_name: grafana
    build: ./requirements/bonus/grafana
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - prometheus


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jul/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jul/data/mariadb'



networks:
    inception:
      driver: bridge